### ISSUE TITLE
does not delete old .files

### ISSUE THREAD

**Issue by ghost** [ganglio/dotfiles#1]
Perhaps put an option in the install.sh such that the user can chose to completely replace their dotfiles or not.

**Comment by ganglio** [comment]
I have improved the installation script.
It now backs up everything that overwrites appending the current timestamp to the new name.

Can you please give it a try and, if happy, close the issue?

Anyway, if you want, you can fork, fix and send me a pull request. :D

**Comment by ghost** [comment]
Thanks! Seems, to work!
