### ISSUE TITLE
unknown

### ISSUE THREAD

**Issue by Pezzekazil** [ganglio/dotfiles#3]
After using the curl command for installation, upon any command i run i get :

Signal 18 (CONT) caught by ps (procps-ng version 3.3.9).  
ps:display.c:66: please report this bug

Is it a zsh problem or something with the rc files?
PS, my bash.bashrc file was empty before the installation.

Thanks in advance.

**Comment by ganglio** [comment]
I have never experienced anything like that. What version of ZSH do you have installed on your machine?
