### ISSUE TITLE
tmux exited

### ISSUE THREAD

**Issue by ghost** [ganglio/dotfiles#4]
tmux exit before it starts, on new installs.

~ $ tmux
[exited]
~ $ 62;9;c

**Comment by ghost** [comment]
``` bash
#set-option -g default-command "main > /dev/null 2>&1; reattach-to-user-namespace -l zsh"
```

commenting this out in tmux.conf seems to fix the issue

**Comment by ganglio** [comment]
I have fixed the bug adding a check in the tmux.conf file to only execute the line if on Darwin
